package ca.corykruger.magic.magic_library.card;

public enum Type {
	ARTIFACT, CREATURE, ENCHANTMENT, INSTANT, LAND, PLANESWALKER, SORCERY, 
	TRIBAL, PLANE, PHENOMENON, VANGUARD, SCHEME, CONSPIRACY;
}
